# Generated by Django 6.1.1 on 2026-09-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
